AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for API Gateway integrated with Lambda to query AI agent

Resources:
  InvokeAgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: src/invoke_agent/
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          AGENT_ID: !Ref AgentId
          ALIAS_ID: !Ref AliasId

      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - bedrock:InvokeAgent
            Resource: "*"

      # Integrate Lambda with API Gateway
      Events:
        ApiGatewayEndpoint:
          Type: Api
          Properties:
            Path: /ask    # API endpoint path
            Method: POST  # HTTP method
            RestApiId: !Ref ApiGatewayApi  # Link to the API Gateway

  # API Gateway Definition
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod  # API Gateway stage name
      Cors:  # Set CORS for the API
        AllowMethods: "'POST'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/prod/ask"
    Export:
      Name: ApiUrl

Parameters:
  AgentId:
    Type: String
    Description: "Bedrock Agent ID"
  AliasId:
    Type: String
    Description: "Bedrock Agent Alias ID"
