version = 0.1
[default.deploy.parameters]
stack_name = "ses-contact-api"
resolve_s3 = true
s3_prefix = "ses-contact-api"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DeliverToEmail=\"your_verified_ses_email@example.com\""
image_repositories = []
