AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for API Gateway integrated with Lambda to send emails via SES.

Resources:
  # Lambda Function to Send Emails using SES
  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12  # Set to your Python runtime version
      CodeUri: src/send_to_ses/
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          DELIVER_TO: !Ref DeliverToEmail  # Environmental variable for destination email
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource: "*"

      # Integrate Lambda with API Gateway
      Events:
        ApiGatewayEndpoint:
          Type: Api
          Properties:
            Path: /submit  # API endpoint path
            Method: POST  # HTTP method
            RestApiId: !Ref ApiGatewayApi  # Link to the API Gateway

  # API Gateway Definition
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod  # API Gateway stage name
      Cors:  # Set CORS for the API
        AllowMethods: "'POST'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/prod/submit"
    Export:
      Name: ApiUrl

# Parameter for the recipient email address
Parameters:
  DeliverToEmail:
    Type: String
    Description: "The email address to send contact form submissions to via SES"
